version: '3.8'
name: live-chat

services:
    mongo:
        build:
            context: .
            dockerfile: Dockerfile.mongo
        container_name: live-chat_mongo
        restart: unless-stopped
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
        volumes:
            - mongo-data:/data/db
        networks:
            - live-chat-net-dev
        ports:
            - 27016:27017

    app-server:
        build:
            context: .
            dockerfile: Dockerfile.app-server.dev
        container_name: live-chat_app-server-dev
        working_dir: /home/node/app
        restart: unless-stopped
        networks:
            - live-chat-net-dev
        ports:
            - 8005:8002
        volumes:
            - app-uploads:/home/node/app/static/uploads
            - ./server/src:/home/node/app/src:ro
            - ./server/node_modules:/home/node/app/node_modules:ro
        depends_on:
            - mongo

    app-client:
        build:
            context: .
            dockerfile: Dockerfile.app-client.dev
        container_name: live-chat_app-client-dev
        restart: unless-stopped
        networks:
            - live-chat-net-dev
        ports:
            - 8001:8001
        volumes:
            - ./client/src:/home/node/app/src
            - ./client/node_modules:/home/node/app/node_modules
        depends_on:
            - app-server

networks:
    live-chat-net-dev:
        driver: bridge

volumes:
    mongo-data:
    app-uploads:
